X = "82";
Y = "45";
Z = 45;
A = 45;

document.write("26" + 3);
document.write(typeof 164);
document.write("<br>");
document.write(2E310);
document.write("<br>");
document.write(-2E310);
document.write("<br>");
document.write(5 < 3);
document.write("<br>");
document.write(5 > 3);
console.log(3 + 18);
document.write("<br>");
document.write("yes" == "yes");
document.write("<br>");
document.write("yes" == "no");
document.write("<br>");
document.write(Z === A);
document.write("<br>");
document.write(X === Y);
document.write("<br>");
document.write(X === A);
document.write("<br>");
document.write(X === Y);
document.write("<br>");
document.write(5 < 10 && 8 < 16);
document.write("<br>");
document.write(2 > 4 && 2 < 3);
document.write("<br>");
document.write(!(8 > 3));